fixed a scaling bug. introduced (disabled) native mode to allow better processing of non-rawtherapee processed photos

diff --git a/rawtherapee_scale_from_converted b/rawtherapee_scale_from_converted
--- a/rawtherapee_scale_from_converted
+++ b/rawtherapee_scale_from_converted
@@ -36,7 +36,7 @@ function compute_scale() {
         local -r original_value=$(lookup_image_width_from_exif "$photofile")
     fi
 
-    bc <<<"scale=4; $target_value/$original_value" | awk '{printf "%f", $0}'
+    bc <<<"scale=4; $target_value/$original_value"
 }
 
 function prepare_scaling_profile() {
@@ -65,8 +65,13 @@ function prepare_scaling_profile() {
         DeconvIterations=100"
 }
 
-while getopts "c:q:hp:o" opt; do
+while getopts "nc:q:hp:o" opt; do
     case $opt in
+        # in NATIVE_MODE, we assume that the given jpeg file was created by Rawtherapee and
+        # that we can find both the original photo file (maybe in raw format) and the sidecar
+        # file. The scaling is then done from the original photo file and the sidecar (pp3).
+        n )
+            declare -r NATIVE_MODE=;;
         c )
             # 1-100
             declare -r JPEG_COMPRESSION=$OPTARG;;
@@ -81,39 +86,52 @@ while getopts "c:q:hp:o" opt; do
 done
 shift $(expr $OPTIND - 1 )
 
+test -v NATIVE_MODE || declare -r NATIVE_MODE=
+
 if (( $# < 3 )); then
     echo "[ERROR] Missing parameter, given parameters are: $@" >&2
     exit 1
 fi
 
+# the width (default) or height (if passing "-h") to
 # FIXME check if valid number   
 scale_to=$1
 
-converted_file=$2
-if ! [[ -e $converted_file ]]; then
-    echo "[ERROR] converted file ${2+$2 }does not exist" >&2
+jpeg_file=$2
+if ! [[ -e $jpeg_file ]]; then
+    echo "[ERROR] converted file ${2+$2 } does not exist" >&2
     exit 1
 fi
 
+# can be a directory or a file
 target=$3
 
-scale=$(compute_scale "$converted_file" "$scale_to")
+scale=$(compute_scale "$jpeg_file" "$scale_to")
 prepare_scaling_profile "$scale" > "$SCALING_PROFILE_FILE"
 
 # TODO check if target width or height are larger than actual height or width of the source. don't
 # apply any scaling in that case, only copy the image file unchanged
 
-original=$(find_original_of_converted "$converted_file")
-if [[ -z $original ]]; then
-    echo "[ERROR] Could not find original file for converted file $converted_file" >&2
-    exit 1
-fi
-conversion_profile=$(find_sidecar_of_converted "$converted_file")
-if [[ -z $conversion_profile ]]; then
-    echo "[ERROR] No conversion profile found for $converted_file" >&2
-    exit 1
+# TODO if we're not in NATIVE_MODE, check if jpeg_file is already compressed
+#   -> use  identify -format '%Q\n' $jpeg_file 
+# if quality is less than N (95?), do not recompress
+
+
+if [[ -v NATIVE_MODE ]]; then
+    source=$(find_original_of_converted "$jpeg_file")
+    if [[ -z $source ]]; then
+        echo "[ERROR] Could not find original file matching $jpeg_file" >&2
+        exit 1
+    fi
+    conversion_profile=$(find_sidecar_of_converted "$jpeg_file")
+    if [[ -z $conversion_profile ]]; then
+        echo "[ERROR] No conversion profile matching $jpeg_file" >&2
+        exit 1
+    fi    
+else 
+    source=$jpeg_file
 fi
 
-rt_process ${OVERWRITE+-o} -p "$conversion_profile" -p "$SCALING_PROFILE_FILE" \
+rt_process ${OVERWRITE+-o} ${NATIVE_MODE+-p "$conversion_profile"} -p "$SCALING_PROFILE_FILE" \
     ${JPEG_COMPRESSION+-c $JPEG_COMPRESSION} ${JPEG_QUALITY+-q $JPEG_QUALITY} \
-    "$original" "$target"
+    "$source" "$target"
